[[mgr.prepend_keymap]]
on  = [ "a" ]
run = "noop"

[[mgr.prepend_keymap]]
on   = [ "i" ]
run  = "create"
desc = "Cd to ~/dotfiles"

[[mgr.prepend_keymap]]
on   = [ "g", "." ]
run  = "cd ~/dotfiles"
desc = "Cd to ~/dotfiles"

[[mgr.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd /mnt/c/Users/schoening_c"
desc = "Cd to Windows Home"
