require("core.keymaps")
require("core.lsp")
require("core.options")

require("plugins/blink")
require("plugins/conform")
require("plugins/colorschema")
require("plugins/fzf")
require("plugins/lsp")
require("plugins/nvim-treesitter")
require("plugins/heirline")
require("plugins/which-key")
require("plugins/yazi")
