return {
	{
		"neovim/nvim-lspconfig",
	},
	{
		-- "hrsh7th/nvim-cmp",
		-- event = { "InsertEnter", "CmdlineEnter" },
		-- dependencies = {
		-- 	"hrsh7th/cmp-buffer",
		-- 	"hrsh7th/cmp-cmdline",
		-- 	"hrsh7th/cmp-emoji",
		-- 	"hrsh7th/cmp-nvim-lsp",
		-- 	"hrsh7th/cmp-path",
		-- 	"L3MON4D3/LuaSnip",
		-- 	"saadparwaiz1/cmp_luasnip",
		-- },
		-- config = function()
		-- 	local cmp = require("cmp")
		-- 	local select_opts = { behavior = cmp.SelectBehavior.Select }
		--
		-- 	cmp.setup({
		-- 		snippet = {
		-- 			expand = function(args)
		-- 				require("luasnip").lsp_expand(args.body)
		-- 			end,
		-- 		},
		-- 		formatting = {
		-- 			fields = { "abbr", "kind" },
		-- 		},
		-- 		sources = {
		-- 			{ name = "path" },
		-- 			{ name = "nvim_lsp", keyword_length = 1 },
		-- 			{ name = "emoji" },
		-- 			{ name = "buffer", keyword_length = 3 },
		-- 			{ name = "luasnip", keyword_length = 2 },
		-- 		},
		-- 		mapping = cmp.mapping.preset.insert({
		-- 			["<C-Space>"] = cmp.mapping.complete(),
		-- 			--
		-- 			["<C-k>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
		-- 			["<C-j>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
		-- 			--
		-- 			["<TAB>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
		-- 			["<S-TAB>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
		-- 			--
		-- 			["<C-u>"] = cmp.mapping.scroll_docs(-4),
		-- 			["<C-d>"] = cmp.mapping.scroll_docs(4),
		-- 			["<CR>"] = cmp.mapping.confirm({ select = false }),
		-- 		}),
		-- 		preselect = "item",
		-- 		completion = {
		-- 			completeopt = "menu,menuone,noinsert",
		-- 		},
		-- 		experimental = {
		-- 			ghost_text = true,
		-- 		},
		-- 	})
		--
		-- 	cmp.setup.cmdline("/", {
		-- 		mappings = cmp.mapping.preset.cmdline(),
		-- 		sources = cmp.config.sources({
		-- 			{ name = "buffer" },
		-- 		}),
		-- 	})
		--
		-- 	cmp.setup.cmdline(":", {
		-- 		mapping = cmp.mapping.preset.cmdline(),
		-- 		sources = cmp.config.sources({
		-- 			{ name = "path" },
		-- 			{ name = "cmdline" },
		-- 		}),
		-- 		matching = {
		-- 			disallow_symbol_nonprefix_matching = false,
		-- 		},
		-- 	})
		-- end,
	},
}
